const fs = require('fs');
const path = require('path');

/**
 * Defensive utility that checks both nested objects (metricObj.values[key])
 * and flat structures (metricObj[key]) to extract k6 metric values safely.
 *
 * @param {Object} metricObj - The k6 metric object
 * @param {string} key - The metric property key to retrieve (e.g. 'rate', 'count', 'avg', 'p(95)')
 * @returns {number} The extracted metric value or 0 if undefined
 */
function getMetricValue(metricObj, key) {
  if (!metricObj || typeof metricObj !== 'object') {
    return 0;
  }

  // 1. Check nested structure: metricObj.values[key]
  if (metricObj.values && typeof metricObj.values === 'object') {
    if (metricObj.values[key] !== undefined && metricObj.values[key] !== null) {
      return Number(metricObj.values[key]);
    }
  }

  // 2. Check flat structure: metricObj[key]
  if (metricObj[key] !== undefined && metricObj[key] !== null) {
    return Number(metricObj[key]);
  }

  // 3. Fallbacks for alternate key names
  if (key === 'p(95)' || key === 'p95') {
    const p95Candidates = ['p(95)', 'p95', '95.0', 'p(90)'];
    for (const altKey of p95Candidates) {
      if (metricObj.values && metricObj.values[altKey] !== undefined) {
        return Number(metricObj.values[altKey]);
      }
      if (metricObj[altKey] !== undefined) {
        return Number(metricObj[altKey]);
      }
    }
  }

  if (key === 'rate') {
    const rateCandidates = ['rate', 'value'];
    for (const altKey of rateCandidates) {
      if (metricObj.values && metricObj.values[altKey] !== undefined) {
        return Number(metricObj.values[altKey]);
      }
      if (metricObj[altKey] !== undefined) {
        return Number(metricObj[altKey]);
      }
    }
  }

  return 0;
}

function parseK6Summary() {
  const summaryFilePath = process.argv[2] || process.env.K6_SUMMARY_PATH || 'summary.json';

  console.log(`Reading k6 summary from: ${summaryFilePath}`);

  if (!fs.existsSync(summaryFilePath)) {
    console.error(`Error: Summary file not found at ${summaryFilePath}`);
    process.exit(1);
  }

  let rawData;
  try {
    rawData = fs.readFileSync(summaryFilePath, 'utf8');
  } catch (err) {
    console.error(`Error reading file: ${err.message}`);
    process.exit(1);
  }

  let summary;
  try {
    summary = JSON.parse(rawData);
  } catch (err) {
    console.error(`Error parsing JSON summary: ${err.message}`);
    process.exit(1);
  }

  const metrics = (summary && summary.metrics) ? summary.metrics : {};

  // Safely extract throughput and request counts
  const totalRequests = getMetricValue(metrics.http_reqs, 'count');
  const throughputRPS = getMetricValue(metrics.http_reqs, 'rate');

  // Latency metrics (in ms)
  const avgLatency = getMetricValue(metrics.http_req_duration, 'avg');
  const minLatency = getMetricValue(metrics.http_req_duration, 'min');
  const maxLatency = getMetricValue(metrics.http_req_duration, 'max');
  const p95Latency = getMetricValue(metrics.http_req_duration, 'p(95)');

  // Failure and assertion check rates
  const failureRateVal = getMetricValue(metrics.http_req_failed, 'rate');
  const failureRatePct = (failureRateVal * 100).toFixed(2);

  const checkRateVal = getMetricValue(metrics.checks, 'rate');
  const checkPassPct = (checkRateVal * 100).toFixed(2);

  // Status checks against thresholds
  const p95Status = p95Latency < 1500 ? '✅ PASSED' : '❌ FAILED';
  const failureStatus = failureRateVal < 0.05 ? '✅ PASSED' : '❌ FAILED';
  const checkStatus = checkRateVal >= 0.95 ? '✅ PASSED' : '⚠️ WARNING';

  const overallStatus = (p95Latency < 1500 && failureRateVal < 0.05) ? '✅ PASS' : '❌ FAIL';

  // Build Markdown Executive Summary Table
  const markdownSummary = `## 📈 SocialShield API Load Test Executive Summary

**Overall Performance Status:** ${overallStatus}

| Metric | Measured Value | Threshold / Target | Status |
| :--- | :--- | :--- | :--- |
| **Total Requests Sent** | \`${totalRequests.toLocaleString()}\` | N/A | ℹ️ Info |
| **Throughput (RPS)** | \`${throughputRPS.toFixed(2)} req/s\` | Baseline | ⚡ Active |
| **Average Latency** | \`${avgLatency.toFixed(2)} ms\` | N/A | ℹ️ Info |
| **Min Latency** | \`${minLatency.toFixed(2)} ms\` | N/A | ℹ️ Info |
| **Max Latency** | \`${maxLatency.toFixed(2)} ms\` | N/A | ℹ️ Info |
| **p95 Latency** | \`${p95Latency.toFixed(2)} ms\` | \`< 1500.00 ms\` | ${p95Status} |
| **Request Failure Rate** | \`${failureRatePct}%\` | \`< 5.00%\` | ${failureStatus} |
| **Assertion Pass Rate** | \`${checkPassPct}%\` | \`≥ 95.00%\` | ${checkStatus} |

### 🛠 Test Configuration Details
- **Virtual Users (VUs):** 100
- **Duration:** 1 minute (60s)
- **Target App:** SocialShield FastAPI Backend
- **Engine:** k6 Load Testing Suite

---
*Report auto-generated by SocialShield Defensive JSON Parser script.*
`;

  console.log('\n' + markdownSummary);

  // Output to GITHUB_STEP_SUMMARY if available
  const githubStepSummaryPath = process.env.GITHUB_STEP_SUMMARY;
  if (githubStepSummaryPath) {
    try {
      fs.appendFileSync(githubStepSummaryPath, markdownSummary + '\n');
      console.log(`Successfully published report to GITHUB_STEP_SUMMARY: ${githubStepSummaryPath}`);
    } catch (err) {
      console.error(`Failed to write to GITHUB_STEP_SUMMARY: ${err.message}`);
    }
  } else {
    console.log('GITHUB_STEP_SUMMARY environment variable not set. Logged summary to stdout.');
  }
}

if (require.main === module) {
  parseK6Summary();
}

module.exports = { getMetricValue, parseK6Summary };
