import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'SocialShield',
      'hello': 'Hello',
      'security_dashboard': 'Security Dashboard',
      'device_security_score': 'Device Security Score',
      'total_scans': 'Total Scans',
      'threats_blocked': 'Threats Blocked',
      'recent_activity': 'Recent Activity',
      'view_all': 'View All',
      'no_recent_scans': 'No recent scans found.',
      'analyzed': 'Analyzed',
      'confidence': 'Confidence',
      'dashboard': 'Dashboard',
      'scan': 'Scan',
      'analytics': 'Analytics',
      'profile': 'Profile',
      'settings': 'Settings',
      'emergency_call': 'Emergency Call',
      'call_police_confirm': 'Call Police Emergency Number (100)?',
      'cancel': 'Cancel',
      'call': 'Call',
      'ai_processing': 'AI Processing',
      'local_processing': 'Local Processing (Recommended)',
      'cloud_processing': 'Cloud Processing',
      'hybrid_processing': 'Hybrid Processing',
      'active_status': 'Active',
      'language': 'Language',
      'notifications': 'Notifications',
      'custom_sound': 'Custom Notification Sound',
      'enable_sound': 'Enable Sound',
      'volume': 'Volume',
      'preview': 'Preview',
      'about_app': 'About SocialShield',
      'version': 'Version 1.0.0',
      'privacy_policy': 'Privacy Policy',
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'signup': 'Sign Up',
      'google_signin': 'Continue with Google',
      'logout': 'Logout',
      'dont_have_account': "Don't have an account? Sign Up",
      'already_have_account': 'Already have an account? Login',
      'forgot_password': 'Forgot Password?',
      'send_reset_link': 'Send Reset Link',
      'back_to_login': 'Back to Login',
      'safe_profiles': 'Safe Profiles',
      'fake_profiles': 'Fake Profiles',
      'scam_alerts': 'Scam Alerts',
      'total_safe_profiles': 'Total Safe Profiles',
      'recent_safe_profiles': 'Recent Safe Profiles',
      'total_fake_profiles': 'Total Fake Profiles',
      'recent_fake_profiles': 'Recent Fake Profiles',
      'scam_alert_warning': 'A suspicious profile has been detected by the community. Please remain cautious.',
    },
    'te': {
      'app_title': 'সোషల్ ഷീൽഡ്',
      'hello': 'హలో',
      'security_dashboard': 'సెక్యూరిటీ డాష్‌బోర్డ్',
      'device_security_score': 'పరిಕರ భದ್ರತಾ స్కోరు',
      'total_scans': 'మొತ್ತం స్ಕಾన్లు',
      'threats_blocked': 'బ్లాక్ చేయబడిన ముప్పులు',
      'recent_activity': 'ఇటీവలి కార్యాచరణ',
      'view_all': 'అన్నీ చూడు',
      'no_recent_scans': 'ఇటీവలి స్ಕಾన్లు ఏవీ కనుగొనబడలేదు.',
      'analyzed': 'ವಿಶ್ಲೇಷಿಸಲಾಗಿದೆ',
      'confidence': 'ನಂಬಿಕೆ',
      'dashboard': 'డాష్‌బోర్ড',
      'scan': 'స్కాన్',
      'analytics': 'ವಿಶ್ಲೇಷಣೆ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'settings': 'సెట్టింగులు',
      'emergency_call': 'అత్యవసర కాల్',
      'call_police_confirm': 'പോലീസ് അടിയന്തിര നമ്പറിലേക്ക് (100) വിളിക്കണോ?',
      'cancel': 'రద్దు చేయి',
      'call': 'కాల్ చేయి',
      'ai_processing': 'AI ప్రాസസ്സിംഗ്',
      'local_processing': 'ಸ್ಥానిక ప్రాసెసింగ్ (సిఫార్సు చేయబడింది)',
      'cloud_processing': 'ಕ್ಲೌಡ್ ಪ್ರೊಸೆസിംഗ്',
      'hybrid_processing': 'ഹൈബ്രിഡ് പ്രോസസ്സിംഗ്',
      'active_status': 'క్రియాశీలంగా ఉంది',
      'language': 'భాഷ',
      'notifications': 'నోటిఫिकేషన్లు',
      'custom_sound': 'അനുയോജ്യമായ അറിയിപ്പ് ശബ്ദം',
      'enable_sound': 'ശബ്ദം പ്രവർത്തനക്ഷമമാക്കുക',
      'volume': 'వాల్యూమ్',
      'preview': 'പ്രിവ്യൂ',
      'about_app': 'సోషల్ షీల్డ్ గురించి',
      'version': 'వెర్షన్ 1.0.0',
      'privacy_policy': 'గోప్యతా విధానం',
      'login': 'లాగిన్',
      'email': 'ఈమెయిల్',
      'password': 'పాస్‌వర్డ్',
      'name': 'పేరు',
      'signup': 'సైన్ అప్',
      'google_signin': 'గూగుల్ తో కొనసాగించండి',
      'logout': 'లాగ్ అవుట్',
      'dont_have_account': "ఖాతా లేదా? సైన్ అప్ చేయండి",
      'already_have_account': 'ఇప్పటికే ఖాతా ఉందా? లాగిన్ అవ్వండి',
      'forgot_password': 'పాಸ್‌వర్డ్ మర్చిపోయారా?',
      'send_reset_link': 'రీసెట్ లింక్ పంపండి',
      'back_to_login': 'తిరిగి లాగిన్ కి వెళ్ళండి',
      'safe_profiles': 'ಸುರಕ್ಷಿತ ಪ್ರೊಫೈಲ್ಗಳು',
      'fake_profiles': 'നകിരി പ്രൊഫൈൽസ്',
      'scam_alerts': 'സ്കാം മുന്നറിയിപ്പുകൾ',
      'total_safe_profiles': 'మొత్తం సురಕ್ಷిత ప్రೊఫైల్స్',
      'recent_safe_profiles': 'ఇటీವలి సురಕ್ಷిత ప్రೊఫైల్స్',
      'total_fake_profiles': 'మొత్తం నకిలీ ప్రೊఫైల్స్',
      'recent_fake_profiles': 'ఇటీವలి నకిలీ ప్రೊఫైల్స్',
      'scam_alert_warning': 'సంఘం ద్వారా ఒక అనుమానాస్పద ప్రൊఫైల్ కనుగొనబడింది. దయచేసి జాగ్రత్తగా ఉండండి.',
    },
    'hi': {
      'app_title': 'सोशलशील्ड',
      'hello': 'नमस्ते',
      'security_dashboard': 'सुरक्षा डैशबोर्ड',
      'device_security_score': 'डिवाइस सुरक्षा स्कोर',
      'total_scans': 'कुल स्कैन',
      'threats_blocked': 'अवरुद्ध खतरे',
      'recent_activity': 'हाल की गतिविधि',
      'view_all': 'सभी देखें',
      'no_recent_scans': 'कोई हालिया स्कैन नहीं मिला।',
      'analyzed': 'विश्लेषण किया गया',
      'confidence': 'आत्मविश्वास',
      'dashboard': 'डैशबोर्ड',
      'scan': 'स्कैन',
      'analytics': 'विश्लेषण',
      'profile': 'प्रोफ़ाइल',
      'settings': 'सेटिंग्स',
      'emergency_call': 'आपातकालीन कॉल',
      'call_police_confirm': 'पुलिस आपातकालीन नंबर (100) पर कॉल करें?',
      'cancel': 'रद्द करें',
      'call': 'कॉल करें',
      'ai_processing': 'एआई प्रोसेसिंग',
      'local_processing': 'स्थानीय प्रोसेसिंग (अनुशंसित)',
      'cloud_processing': 'क्लाउड प्रोसेसिंग',
      'hybrid_processing': 'हाइब्रिड प्रोसेसिंग',
      'active_status': 'सक्रिय',
      'language': 'भाषा',
      'notifications': 'सूचनाएं',
      'custom_sound': 'कस्टम अधिसूचना ध्वनि',
      'enable_sound': 'ध्वनि सक्षम करें',
      'volume': 'आवाज',
      'preview': 'पूर्वावलोकन',
      'about_app': 'सोशलशील्ड के बारे में',
      'version': 'संस्करण 1.0.0',
      'privacy_policy': 'गोपनीयता नीति',
      'login': 'लॉगिन',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'name': 'नाम',
      'signup': 'साइन अप',
      'google_signin': 'गूगल के साथ जारी रखें',
      'logout': 'लॉगआउट',
      'dont_have_account': "खाता नहीं है? साइन अप करें",
      'already_have_account': 'पहले से ही खाता है? लॉगिन करें',
      'forgot_password': 'पासवर्ड भूल गए?',
      'send_reset_link': 'रीसेट लिंक भेजें',
      'back_to_login': 'लॉगिन पर वापस जाएं',
      'safe_profiles': 'सुरक्षित प्रोफ़ाइल',
      'fake_profiles': 'फर्जी प्रोफ़ाइल',
      'scam_alerts': 'स्कैम अलर्ट',
      'total_safe_profiles': 'कुल सुरक्षित प्रोफ़ाइल',
      'recent_safe_profiles': 'हाल की सुरक्षित प्रोफ़ाइल',
      'total_fake_profiles': 'कुल फर्जी प्रोफ़ाइल',
      'recent_fake_profiles': 'हाल की फर्जी प्रोफ़ाइल',
      'scam_alert_warning': 'समुदाय द्वारा एक संदिग्ध प्रोफ़ाइल का पता चला है। कृपया सतर्क रहें।',
    },
    'ta': {
      'app_title': 'சோஷியல்ஷீல்டு',
      'hello': 'வணக்கம்',
      'security_dashboard': 'பாதுகாப்பு டாஷ்போர்டு',
      'device_security_score': 'சாதன பாதுகாப்பு மதிப்பெண்',
      'total_scans': 'மொத்த ஸ்கேன்கள்',
      'threats_blocked': 'தடுக்கப்பட்ட அச்சுறுத்தல்கள்',
      'recent_activity': 'சமீபத்திய நடவடிக்கை',
      'view_all': 'அனைத்தையும் காண்க',
      'no_recent_scans': 'சமீபத்திய ஸ்கேன்கள் எதுவும் இல்லை.',
      'analyzed': 'பகுப்பாய்வு செய்யப்பட்டது',
      'confidence': 'நம்பிக்கை',
      'dashboard': 'டாஷ்போர்டு',
      'scan': 'ஸ்கேன்',
      'analytics': 'பகுப்பாய்வு',
      'profile': 'சுயவிவரம்',
      'settings': 'அமைப்புகள்',
      'emergency_call': 'அவசர அழைப்பு',
      'call_police_confirm': 'காவல்துறை அவசர எண் (100) ஐ அழைக்கவா?',
      'cancel': 'ரத்துசெய்',
      'call': 'அழைக்கவும்',
      'ai_processing': 'AI செயலாக்கம்',
      'local_processing': 'உள்ளூர் செயலாக்கம் (பரிந்துரைக்கப்படுகிறது)',
      'cloud_processing': 'கிளவுட் செயலாக்கம்',
      'hybrid_processing': 'ஹைப்ரிட் செயலாக்கம்',
      'active_status': 'செயலில் உள்ளது',
      'language': 'மொழி',
      'notifications': 'அறிவிப்புகள்',
      'custom_sound': 'தனிப்பயன் அறிவிப்பு ஒலி',
      'enable_sound': 'ஒலியை இயக்கு',
      'volume': 'ஒலி அளவு',
      'preview': 'முன்னோட்டம்',
      'about_app': 'சோஷியல்ஷீல்டு பற்றி',
      'version': 'பதிப்பு 1.0.0',
      'privacy_policy': 'தனியுரிமைக் கொள்கை',
      'login': 'உள்நுழை',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'name': 'பெயர்',
      'signup': 'பதிவு செய்',
      'google_signin': 'கூகுள் மூலம் தொடரவும்',
      'logout': 'வெளியேறு',
      'dont_have_account': "கணக்கு இல்லையா? பதிவு செய்",
      'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக',
      'forgot_password': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
      'send_reset_link': 'மறுஅமைப்பு இணைப்பை அனுப்பு',
      'back_to_login': 'உள்நுழைவுக்குத் திரும்பு',
      'safe_profiles': 'பாதுகாப்பான சுயவிவரங்கள்',
      'fake_profiles': 'போலி சுயவிவரங்கள்',
      'scam_alerts': 'மோசடி எச்சரிக்கைகள்',
      'total_safe_profiles': 'மொத்த பாதுகாப்பான சுயவிவரங்கள்',
      'recent_safe_profiles': 'சமீபத்திய பாதுகாப்பான சுயவிவரங்கள்',
      'total_fake_profiles': 'மொத்த போலி சுயವಿவரங்கள்',
      'recent_fake_profiles': 'சமீபத்திய போலி சுயವಿவரங்கள்',
      'scam_alert_warning': 'சமூகத்தால் ஒரு சந்தேகத்திற்கிடமான சுயவிவரம் கண்டறியப்பட்டுள்ளது. தயவுசெய்து எச்சரிக்கையாக இருக்கவும்.',
    },
    'kn': {
      'app_title': 'ಸೋಷಿಯಲ್ ಶೀಲ್ಡ್',
      'hello': 'ನಮಸ್ಕಾರ',
      'security_dashboard': 'ಭದ್ರತಾ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'device_security_score': 'ಸಾಧನ ಭದ್ರತಾ ಸ್ಕೋರ್',
      'total_scans': 'ಒಟ್ಟು ಸ್ಕ್ಯಾನ್‌ಗಳು',
      'threats_blocked': 'ತಡೆಹಿಡಿಯಲಾದ ಬೆದರಿಕೆಗಳು',
      'recent_activity': 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
      'view_all': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
      'no_recent_scans': 'ಯಾವುದೇ ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್ ಕಂಡುಬಂದಿಲ್ಲ.',
      'analyzed': 'ವಿಶ್ಲೇಷಿಸಲಾಗಿದೆ',
      'confidence': 'ನಂಬಿಕೆ',
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'scan': 'ಸ್ಕ್ಯಾನ್',
      'analytics': 'ವಿಶ್ಲೇಷಣೆ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
      'emergency_call': 'ತುರ್ತು ಕರೆ',
      'call_police_confirm': 'ಪೊಲೀಸ್ ತುರ್ತು ಸಂಖ್ಯೆಗೆ (100) ಕರೆ ಮಾಡಬೇಕೇ?',
      'cancel': 'ರದ್ದುಮಾಡು',
      'call': 'ಕರೆಮಾಡು',
      'ai_processing': 'AI ಪ್ರೊಸೆಸಿಂಗ್',
      'local_processing': 'ಸ್ಥಳೀಯ ಪ್ರೊಸೆಸಿಂಗ್ (ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ)',
      'cloud_processing': 'ಕ್ಲೌಡ್ ಪ್ರೊಸೆಸಿಂಗ್',
      'hybrid_processing': 'ಹೈಬ್ರಿಡ್ ಪ್ರೊಸೆಸಿಂಗ್',
      'active_status': 'ಸಕ್ರಿಯವಾಗಿದೆ',
      'language': 'ಭಾಷೆ',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'custom_sound': 'ಕಸ್ಟಮ್ ಅಧಿಸೂಚನೆ ಧ್ವನಿ',
      'enable_sound': 'ಧ್ವನಿಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸು',
      'volume': 'ಧ್ವನಿ ಪ್ರಮಾಣ',
      'preview': 'ಮುನ್ನೋಟ',
      'about_app': 'ಸೋಷಿಯಲ್ ಶೀಲ್ಡ್ ಬಗ್ಗೆ',
      'version': 'ಆವೃತ್ತಿ 1.0.0',
      'privacy_policy': 'ಗೌಪ್ಯತಾ ನೀತಿ',
      'login': 'ಲಾಗಿನ್',
      'email': 'ಇಮೇಲ್',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'name': 'ಹೆಸರು',
      'signup': 'ಸೈನ್ ಅಪ್',
      'google_signin': 'ಗೂಗಲ್‌ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'dont_have_account': "ಖಾತೆ ಇಲ್ಲವೇ? ಸೈನ್ ಅಪ್ ಮಾಡಿ",
      'already_have_account': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ',
      'forgot_password': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
      'send_reset_link': 'ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಕಳುಹಿಸಿ',
      'back_to_login': 'ಲಾಗಿನ್‌ಗೆ ಹಿಂತಿರುಗಿ',
      'safe_profiles': 'ಸುರಕ್ಷಿತ ಪ್ರೊಫೈಲ್ಗಳು',
      'fake_profiles': 'ನಕಲಿ ಪ್ರೊಫೈಲ್ಗಳು',
      'scam_alerts': 'ಸ್ಕ್ಯಾಮ್ ಎಚ್ಚರಿಕೆಗಳು',
      'total_safe_profiles': 'ಒಟ್ಟು ಸುರಕ್ಷಿತ ಪ್ರೊಫೈಲ್ಗಳು',
      'recent_safe_profiles': 'ಇತ್ತೀಚಿನ ಸುರಕ್ಷಿತ ಪ್ರೊಫೈಲ್ಗಳು',
      'total_fake_profiles': 'ಒಟ್ಟು ನಕಲಿ ಪ್ರೊಫೈಲ್ಗಳು',
      'recent_fake_profiles': 'ಇತ್ತೀಚಿನ ನಕಲಿ ಪ್ರೊಫೈಲ್ಗಳು',
      'scam_alert_warning': 'ಸಮುದಾಯದಿಂದ ಒಂದು ಶಂಕಿತ ಪ್ರೊಫೈಲ್ ಪತ್ತೆಯಾಗಿದೆ. ದಯವಿಟ್ಟು ಜಾಗರೂಕರಾಗಿರಿ.',
    },
    'ml': {
      'app_title': 'സോഷ്യൽഷീൽഡ്',
      'hello': 'ഹലോ',
      'security_dashboard': 'സെക്യൂരിറ്റി ഡാഷ്‌ബോർഡ്',
      'device_security_score': 'ഉപകരണ സുരക്ഷാ സ്കോർ',
      'total_scans': 'ആകെ സ്കാനുകൾ',
      'threats_blocked': 'തടഞ്ഞ ഭീഷണികൾ',
      'recent_activity': 'സമീപകാല പ്രവർത്തനം',
      'view_all': 'എല്ലാം കാണുക',
      'no_recent_scans': 'സമീപകാല സ്കാനുകളൊന്നും കണ്ടെത്തിയില്ല.',
      'analyzed': 'വിശകലനം ചെയ്തു',
      'confidence': 'ആത്മവിശ്വാസം',
      'dashboard': 'ഡാഷ്‌ബോർഡ്',
      'scan': 'സ്കാൻ',
      'analytics': 'വിശകലനം',
      'profile': 'പ്രൊഫൈൽ',
      'settings': 'സെറ്റിംഗ്സ്',
      'emergency_call': 'അടിയന്തിര കോൾ',
      'call_police_confirm': 'പോലീസ് അടിയന്തിര നമ്പറിലേക്ക് (100) വിളിക്കണോ?',
      'cancel': 'റദ്ദാക്കുക',
      'call': 'വിളിക്കുക',
      'ai_processing': 'AI പ്രോസസ്സിംഗ്',
      'local_processing': 'പ്രാദേശിക പ്രോസസ്സിംഗ് (ശുപാർശ ചെയ്യുന്നത്)',
      'cloud_processing': 'ക്ലൗഡ് പ്രോസസ്സിംഗ്',
      'hybrid_processing': 'ഹൈബ്രിഡ് പ്രോസസ്സിംഗ്',
      'active_status': 'സജീവമാണ്',
      'language': 'ഭാഷ',
      'notifications': 'അറിയിപ്പുകൾ',
      'custom_sound': 'ഇഷ്‌ടാനുസൃത അറിയിപ്പ് ശബ്ദം',
      'enable_sound': 'ശബ്ദം പ്രവർത്തനക്ഷമമാക്കുക',
      'volume': 'ശബ്ദ വ്യാപ്തി',
      'preview': 'പ്രിവ്യൂ',
      'about_app': 'സോഷ്യൽഷീൽഡിനെക്കുറിച്ച്',
      'version': 'പതിപ്പ് 1.0.0',
      'privacy_policy': 'സ്വകാര്യതാ നയം',
      'login': 'ലോഗിൻ',
      'email': 'ഇമെയിൽ',
      'password': 'പാസ്‌വേഡ്',
      'name': 'പേര്',
      'signup': 'സൈൻ അപ്പ്',
      'google_signin': 'ഗൂഗിൾ ഉപയോഗിച്ച് തുടരുക',
      'logout': 'ലോഗ് ഔട്ട്',
      'dont_have_account': "അക്കൗണ്ട് ഇല്ലേ? സൈൻ അപ്പ് ചെയ്യുക",
      'already_have_account': 'ഇതിനകം ഒരു അക്കൗണ്ട് ഉണ്ടോ? ലോഗിൻ ചെയ്യുക',
      'forgot_password': 'പാസ്‌വേഡ് മറന്നുപോയോ?',
      'send_reset_link': 'റീസെറ്റ് ലിങ്ക് അയയ്ക്കുക',
      'back_to_login': 'ലോഗിൻ ചെയ്യുന്നതിലേക്ക് തിരികെ പോകുക',
      'safe_profiles': 'സുരക്ഷിത പ്രൊഫൈലുകൾ',
      'fake_profiles': 'വ്യാജ പ്രൊഫൈലുകൾ',
      'scam_alerts': 'തട്ടിപ്പ് മുന്നറിയിപ്പുകൾ',
      'total_safe_profiles': 'ആകെ സുരക്ഷിത പ്രൊഫൈലുകൾ',
      'recent_safe_profiles': 'സമീപകാല സുരക്ഷിത പ്രൊഫൈലുകൾ',
      'total_fake_profiles': 'ആകെ വ്യാജ പ്രൊഫൈലുകൾ',
      'recent_fake_profiles': 'സമീപകാല വ്യാജ പ്രൊഫൈലുകൾ',
      'scam_alert_warning': 'കമ്മ്യൂണിറ്റി ഒരു സംശയാസ്പദമായ പ്രൊഫൈൽ കണ്ടെത്തിയിട്ടുണ്ട്. ദയവായി ജാഗ്രത പാലിക്കുക.',
    }
  };

  static String translate(String lang, String key) {
    if (!_localizedValues.containsKey(lang)) {
      return _localizedValues['en']?[key] ?? key;
    }
    return _localizedValues[lang]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class LanguageNotifier extends StateNotifier<String> {
  LanguageNotifier() : super('en') {
    _loadLanguage();
  }

  static const String _keyLang = 'selected_language';

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    state = prefs.getString(_keyLang) ?? 'en';
  }

  Future<void> setLanguage(String lang) async {
    state = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_keyLang, lang);
  }
}

final languageProvider = StateNotifierProvider<LanguageNotifier, String>((ref) {
  return LanguageNotifier();
});

class Trans {
  static String of(BuildContext context, String key) {
    final container = ProviderScope.containerOf(context);
    final lang = container.read(languageProvider);
    return LocalizationService.translate(lang, key);
  }
}
